### ISSUE TITLE
Spreadsheet API : cURL error 2: easy handle already used in multi handle (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

### ISSUE THREAD

**Issue by sukhvir1313** [googleworkspace/php-samples#64]
For Google Spreadsheet API, it was running perfectly before 17 April 2020, I have not done any changes to server or code, however it's not working now. Below is Strack Trace for that.

Stack trace:
#0 /home/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /home/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /home/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /home/public_html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleH in /home/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 186

## Expected Behavior
It should return spreadsheet values for given range

## Actual Behavior
Returning curl error: 

cURL error 2: easy handle already used in multi handle (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

## Steps to Reproduce the Problem

  1. Simply run https://github.com/gsuitedevs/php-samples/blob/master/sheets/quickstart/quickstart.php with all required entries/parameters.

## Specifications

  - PHP version (`php -v`): 5.6.40
  - OS (Mac/Linux/Windows): Linux

**Comment by jpoehnelt** [comment]
Closing this issue as the repository is archived.
