### ISSUE TITLE
Example works fine from CLI, but fails when using crontab

### ISSUE THREAD

**Issue by gshafer** [googleworkspace/php-samples#72]
(Please search [existing issues](https://github.com/gsuitedevs/php-samples/issues) before creating a new one.)

**Sample:**

## Expected Behavior

Returns name from spreadsheet

## Actual Behavior
PHP Fatal error:  Uncaught InvalidArgumentException: file "credentials.json" doe
s not exist in /home/george/clock/vendor/google/apiclient/src/Client.php:960
Stack trace:
#0 /home/george/clock/qs.php(33): Google\Client->setAuthConfig()
#1 /home/george/clock/qs.php(79): getClient()
#2 {main}
  thrown in /home/george/clock/vendor/google/apiclient/src/Client.php on line 96
0

## Steps to Reproduce the Problem

  1.run from crontab
  1.
  1.

## Specifications

  - PHP version (`php -v`):v7.4.3
  - OS (Mac/Linux/Windows):Ubuntu 20.1

**Comment by gshafer** [comment]
I fixed the path name to autoload.php: 

require '/home/george/clock/vendor/autoload.php';

Now error is:

PHP Fatal error:  Uncaught InvalidArgumentException: file "credentials.json" does not exist in /home/george/clock/vendor/google/apiclient/src/Client.php:960
Stack trace:
#0 /home/george/clock/qs.php(33): Google\Client->setAuthConfig()
#1 /home/george/clock/qs.php(79): getClient()
#2 {main}
  thrown in /home/george/clock/vendor/google/apiclient/src/Client.php on line 960

**Comment by gshafer** [comment]
My bad. Fixed the path to credentials.php and OK now.
