### ISSUE TITLE
PHP Quickstart Classroom API

### ISSUE THREAD

**Issue by Mounir0Maaroufi** [googleworkspace/php-samples#76]
php quickstart.php

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'missing the required redirect URI' in C:\wamp64\www\google classeroom\vendor\google\auth\src\OAuth2.php:637
Stack trace:
#0 C:\wamp64\www\google classeroom\vendor\google\apiclient\src\Google\Client.php(328): Google\Auth\OAuth2->buildFullAuthorizationUri(Array)
#1 C:\wamp64\www\google classeroom\quickstart.php(38): Google_Client->createAuthUrl()
#2 C:\wamp64\www\google classeroom\quickstart.php(63): getClient()
#3 {main}
  thrown in C:\wamp64\www\google classeroom\vendor\google\auth\src\OAuth2.php on line 637

**Comment by jpoehnelt** [comment]
Closing this issue as the repository is archived.
