### ISSUE TITLE
credentials.json fatal error

### ISSUE THREAD

**Issue by halburgiss** [googleworkspace/php-samples#88]
## Expected Behavior

No error. I don't see anything about credentials.json .... what is it, where does it go, etc.

## Actual Behavior

```
$ php quickstart.php 
PHP Fatal error:  Uncaught InvalidArgumentException: file "credentials.json" does not exist in /home/hal/public_html/google_cloud/apiclient/vendor/google/apiclient/src/Client.php:980
Stack trace:
#0 /home/hal/public_html/google_cloud/apiclient/quickstart.php(33): Google\Client->setAuthConfig()
#1 /home/hal/public_html/google_cloud/apiclient/quickstart.php(79): getClient()
#2 {main}
  thrown in /home/hal/public_html/google_cloud/apiclient/vendor/google/apiclient/src/Client.php on line 980

```

## Steps to Reproduce the Problem

  1. Copy/paste sample code to quickstart.php
  2. run as `php quickstart.php`
  

## Specifications

  - PHP version (`php -v`): 7.4.3
  - OS (Mac/Linux/Windows): Ubuntu 20.04

**Comment by bookchiq** [comment]
It is not at all clear from the instructions or the prerequisites themselves, but there's a section at the bottom for Troubleshooting, and in that, [an explanation of the actual prerequisites](https://developers.google.com/calendar/api/quickstart/php#file_not_found_error_for_credentialsjson) (that result in you having a valid credentials.json file).
